version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    build: .
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://markmagdy:XqC7L3kstsTpnHfx@cluster0.gmcanta.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: Task-Manager
      DB_USER: markmagdy
      DB_PASS: XqC7L3kstsTpnHfx
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
# version: "3.1"

# services:
#   app:
#     container_name: docker-node-mongo
#     restart: always
#     build: .
#     ports:
#       - "80:3000"
#     links:
#       - mongo
#       - mongo-express
#   mongo:
#     image: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: markmagdy
#       MONGO_INITDB_ROOT_PASSWORD: XqC7L3kstsTpnHfx

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: markmagdy
#       ME_CONFIG_MONGODB_ADMINPASSWORD: XqC7L3kstsTpnHfx
#       ME_CONFIG_MONGODB_URL: mongodb+srv://markmagdy:XqC7L3kstsTpnHfx@cluster0.gmcanta.mongodb.net/?retryWrites=true&w=majority
# version: "3.9"
# services:
#   mongo_db:
#     container_name: db_container
#     image: mongo:latest
#     restart: always
#     environment:
