version: "3.9"

services:
  mongo_db:
    container_name: DB_container
    image: mongo:latest
    restart: always
    build: .
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://markmagdy:XqC7L3kstsTpnHfx@cluster0.gmcanta.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: Task-Manager
      DB_USER: markmagdy
      DB_PASS: XqC7L3kstsTpnHfx
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
